apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-xxxxxx-your-username
  namespace: app
plugin: key-auth

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-service-xxxxxx-your-username
  namespace: app
  annotations:
    konghq.com/plugins: key-auth-xxxxxx-your-username
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /xxxxxx-your-username
        pathType: Prefix
        backend:
          service:
            name: hello-world-service
            port: 
              number: 80