apiVersion: v1
kind: Secret
metadata:
  name: key-auth-xxxxxx-your-username-secret
  namespace: app
  annotations:
    kubernetes.io/ingress.class: kong
type: Opaque
data:
  kongCredType: a2V5LWF1dGg= 
  key: eHh4eHh4LXlvdXItdXNlcm5hbWUta2V5
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: acl-xxxxxx-your-username-secret
  namespace: app
type: Opaque
data:
  kongCredType: YWNs
  group: eHh4eHh4LXlvdXItdXNlcm5hbWUtYWNsLWdyb3Vw
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: xxxxxx-your-username
  namespace: app
  annotations:
    kubernetes.io/ingress.class: kong
username: xxxxxx-your-username
credentials:
- key-auth-xxxxxx-your-username-secret
- acl-xxxxxx-your-username-secret
